version: '3.7'
services:
  django-tutorial:
    container_name: django-tutorial
    image: $IMAGE_NAME:$BUILD_NUMBER
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      DJANGO_HOST: bd_mariadb_django_jenkins
      DJANGO_USER: django
      DJANGO_PASSWORD: django
      DJANGO_DB: django
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.org
    ports:
      - 8084:8006
    depends_on:
      - db_django_jenkins
  db_django_jenkins:
    container_name: bd_mariadb_django_jenkins
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django
    volumes:
      - mariadb_data_django_jenkins:/var/lib/mysql
volumes:
    mariadb_data_django_jenkins:
